"""Initial migration create all tables

Revision ID: aaa00a9abfe5
Revises: 
Create Date: 2025-09-22 13:26:58.927669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa00a9abfe5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GridConfig',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True, comment='策略名称'),
    sa.Column('last_modified', sa.DateTime(), nullable=True, comment='最后修改时间'),
    sa.Column('a', sa.Float(), nullable=False, comment='波动大小参数 a'),
    sa.Column('b', sa.Float(), nullable=False, comment='单行收益率参数 b'),
    sa.Column('first_trigger_price', sa.Float(), nullable=False, comment='首行买入触发价'),
    sa.Column('total_rows', sa.Integer(), nullable=False, comment='网格总行数'),
    sa.Column('buy_amount', sa.Float(), nullable=False, comment='买入金额'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GridData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='日期'),
    sa.Column('index_code', sa.String(length=50), nullable=False, comment='指数代码'),
    sa.Column('index_chinese_full_name', sa.String(length=100), nullable=False, comment='指数中文全称'),
    sa.Column('index_chinese_short_name', sa.String(length=50), nullable=False, comment='指数中文简称'),
    sa.Column('index_english_full_name', sa.String(length=100), nullable=False, comment='指数英文全称'),
    sa.Column('index_english_short_name', sa.String(length=50), nullable=False, comment='指数英文简称'),
    sa.Column('open_price', sa.Float(), nullable=False, comment='开盘价'),
    sa.Column('high_price', sa.Float(), nullable=False, comment='最高价'),
    sa.Column('low_price', sa.Float(), nullable=False, comment='最低价'),
    sa.Column('close_price', sa.Float(), nullable=False, comment='收盘价'),
    sa.Column('change', sa.Float(), nullable=False, comment='涨跌'),
    sa.Column('change_percent', sa.Float(), nullable=False, comment='涨跌幅(%)'),
    sa.Column('volume_m_shares', sa.Float(), nullable=False, comment='成交量(万手)'),
    sa.Column('turnover', sa.Float(), nullable=False, comment='成交金额(亿元)'),
    sa.Column('cons_number', sa.Integer(), nullable=False, comment='样本数量'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GridRow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False, comment='所属配置ID'),
    sa.Column('fall_percent', sa.Float(), nullable=False, comment='跌幅比例'),
    sa.Column('level_ratio', sa.Float(), nullable=False, comment='档位值'),
    sa.Column('buy_trigger_price', sa.Float(), nullable=False, comment='买入触发价'),
    sa.Column('buy_price', sa.Float(), nullable=False, comment='买入交易价'),
    sa.Column('buy_amount', sa.Float(), nullable=False, comment='买入金额'),
    sa.Column('shares', sa.Float(), nullable=False, comment='买入股数'),
    sa.Column('sell_trigger_price', sa.Float(), nullable=False, comment='卖出触发价'),
    sa.Column('sell_price', sa.Float(), nullable=False, comment='卖出交易价'),
    sa.Column('yield_rate', sa.Float(), nullable=False, comment='收益率'),
    sa.Column('profit_amount', sa.Float(), nullable=False, comment='盈利金额'),
    sa.ForeignKeyConstraint(['config_id'], ['GridConfig.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GridRow')
    op.drop_table('GridData')
    op.drop_table('GridConfig')
    # ### end Alembic commands ###
