"""Remove index_english_short_name from GridData

Revision ID: 0208455daa63
Revises: 1cded23f365d
Create Date: 2025-10-26 23:20:55.136917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0208455daa63'
down_revision: Union[str, Sequence[str], None] = '1cded23f365d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GridData', 'index_english_short_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GridData', sa.Column('index_english_short_name', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
