"""add name and last_modified

Revision ID: d291587e96a7
Revises: 
Create Date: 2025-09-19 12:57:07.643064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd291587e96a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 name 字段
    op.add_column('GridConfig', sa.Column('name', sa.String(length=100), nullable=True, comment="策略名称"))
    # 添加 last_modified 字段
    op.add_column('GridConfig', sa.Column('last_modified', sa.DateTime(), nullable=True, comment="最后修改时间"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('GridConfig', 'last_modified')
    op.drop_column('GridConfig', 'name')
    # ### end Alembic commands ###
